### ISSUE TITLE
Sample 008-dotnet-nl2sql Issues

### ISSUE THREAD

**Issue by aaronwittman** [microsoft/semantic-memory#25]
A couple of issues to help new downloaders.

- The Semantic functions are in the wrong folders, as they are reversed.
- minRelevanceScore: 0.75, found nothing, had to change to 0.5, might be good to change the default to be lower for the sample.
- Path (I just saw this has been fixed)

**Comment by geffzhang** [comment]
I also ran into the same issue.

**Comment by crickman** [comment]
Thank you for exploring this tool and the follow-up.

I'll looking into the prompt definitions/semantic functions.

Agree the relevenace threshold of 0.75 is a bit arbitrarary, moving the value to a configuration setting or command-line parameter (or both) would be more flexible.
