### ISSUE TITLE
add a method to import content as string instead of document

### ISSUE THREAD

**Issue by giannik** [microsoft/semantic-memory#27]
Would it be possible to add a overriden method ImportDocumentContentAsync that would accept as input the string representation of a document instead of the doc file . this helps in integration with our solution that pre-processes the doc and has the string value available.

Instead of 
```
await memory.ImportDocumentAsync("meeting-transcript.docx", tags: new() { { "user", "Blake" } });
```
you could : 

```
await memory.ImportDocumentContentAsync("DocumentContent", tags: new() { { "user", "Blake" } });

```

**Comment by dluc** [comment]
added **string** and **Stream**: https://github.com/microsoft/semantic-memory/commit/4aa666078e554d3a1b36ac4e0731417fbf5e4bc9

examples:

```csharp
await memory.ImportTextAsync(
    "In physics, mass–energy equivalence is the relationship between mass and energy " +
    "in a system's rest frame, where the two quantities differ only by a multiplicative " +
    "constant and the units of measurement. The principle is described by the physicist " +
    "Albert Einstein's formula: E = m*c^2", documentId: "123");
```
