### ISSUE TITLE
How to remove or replace a file from the Document?

### ISSUE THREAD

**Issue by xbotter** [microsoft/semantic-memory#31]
If the file has changed or is no longer needed to be accessed in the current memory.

**Comment by dluc** [comment]
Currently there's no API to directly edit the content of a document, and we use the `ImportDocumentAsync` API to refresh the document, passing the original Document ID, re-uploading the document without the file to remove.

We'll improve this area soon :-)

**Comment by dluc** [comment]
We added the ability to delete documents. It doesn't fully address your question but it might help if you put one file per document.

**Comment by xbotter** [comment]
In my use case, I am trying to use Document as a knowledge database that can be managed in the form of maintaining files.
This requires performing operations to add, delete, and replace files in the Document.

I wonder if this scenario can be supported from semantic memory or if there are better practical methods available?

**Comment by dluc** [comment]
@xbotter have you considere using tags and filters? 

E.g. rather than multiple files in the one document, uploading multiple documents with the same tag:

```csharp
await memory.ImportDocumentAsync(new Document()
            .AddFile("file1.pdf").AddTag("KnowledgeBase", "001"));

await memory.ImportDocumentAsync(new Document()
            .AddFile("file2.pdf").AddTag("KnowledgeBase", "001"));

await memory.ImportDocumentAsync(new Document()
            .AddFile("file3.pdf").AddTag("KnowledgeBase", "001"));

await memory.ImportDocumentAsync(new Document()
            .AddFile("foobar.docx").AddTag("KnowledgeBase", "002"));

var answer = await memory.AskAsync(question, MemoryFilters.ByTag("KnowledgeBase", "001"));
```

**Comment by xbotter** [comment]
Thanks @dluc ,  I have successfully fulfilled my use case based on your suggestions and  [reference documents](https://github.com/microsoft/semantic-memory/blob/main/docs/SECURITY_FILTERS.md).

**Comment by xbotter** [comment]
> We added the ability to delete documents. It doesn't fully address your question but it might help if you put one file per document.

Delete and then re-upload, it worked.
