### ISSUE TITLE
Simple* services not reading directory from configuration

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-memory#58]
Simple* services using hardcoded config values.

**appsettings.json**
```
      "FileSystemContentStorage": {
        "Directory": "C:/Memory/Cache"
      },
      "FileBasedQueue": {
        "Directory": "C:/Memory/Queue"
      }

```

**MemoryClientBuilder.cs**
```
        this.WithSimpleFileStorage(new SimpleFileStorageConfig { Directory = "tmp-memory-files" });
        this.WithSimpleVectorDb(new SimpleVectorDbConfig { Directory = "tmp-memory-vectors" });
```

**Comment by dluc** [comment]
Thank you for your collaboration and contribution to this issue! As the matter at hand appears to be resolved, I'll be closing this issue for now. However, please don't hesitate to reach out if you have any further questions or concerns. We're more than happy to reopen the issue or continue the conversation as needed.

Wishing you all the best, and happy coding! 😊
