### ISSUE TITLE
Orchestrator is not reading the ingestion steps from appsettings

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/semantic-memory#64]
The orchestrator is not reading the ingestion steps from app settings: https://github.com/microsoft/semantic-memory/blob/main/dotnet/CoreLib/Pipeline/BaseOrchestrator.cs#L40. It always consumes the default steps.

**Comment by dluc** [comment]
Fixed :-)

**Comment by TaoChenOSU** [comment]
Creating a note here for using arrays in .NET configuration:

If you have multiple sources for a configuration that is an array, the value of the configuration does NOT get overridden by each source. Instead, the values in the sources will get "merged". See example below.

```
appsettings.json => settings.foo = [ 1, 2, 3, 4, 5, A, B, C ]
appsettings.development.json => settings.foo = [ X, Y, Z ]
```
 
The way .NET handles that, results in

```
settings.foo = [ X, Y, Z, 4, 5, A, B, C ]
```

To avoid unintended behavior in your application if you have arrays in your config, please make sure to keep only config source that has the values and all the other ones should remain empty.
