### ISSUE TITLE
Unable to resolve type IOcrEngine

### ISSUE THREAD

**Issue by MayueCif** [microsoft/semantic-memory#67]
```
var memory = new MemoryClientBuilder()
    .WithOpenAIDefaults(apiKey)
    .WithCustomImageOcr(new TesseractEngineWrapper(new TesseractEngine(tesseractOptions!.FilePath, tesseractOptions!.Language, EngineMode.Default)))
    .WithQdrant($"{qdrantOptions.Host}:{qdrantOptions.Port}")
    .Build();

services.AddSingleton(memory);
```

```
public DocumentController(ILogger<DocumentController> logger,
    IOptions<DocumentOptions> documentOptions,
    IAuthInfo authInfo,
    IOcrEngine ocrEngine,
    DocumentTypeProvider documentTypeProvider)
{
    _logger = logger;
    _documentOptions = documentOptions.Value;
    _authInfo = authInfo;
    _ocrEngine = ocrEngine;
    _documentTypeProvider = documentTypeProvider;
}
```

when di ocrengine to controller,throw exception。
Unable to resolve service for type 'Microsoft.SemanticMemory.DataFormats.Image.IOcrEngine' while attempting to activate 'HaoAI.Service.Controllers.DocumentController'

**Comment by dluc** [comment]
@MayueCif could you try passing `services` to the builder?

```
var memory = new MemoryClientBuilder(services) // <==
    .WithOpenAIDefaults(apiKey)
    .WithCustomImageOcr(new TesseractEngineWrapper(new TesseractEngine(tesseractOptions!.FilePath, tesseractOptions!.Language, EngineMode.Default)))
    .WithQdrant($"{qdrantOptions.Host}:{qdrantOptions.Port}")
    .Build();

services.AddSingleton(memory);
```

**Comment by dluc** [comment]
I added an example about very similar to your scenario, could you try starting from here https://github.com/microsoft/semantic-memory/tree/main/examples/007-aspnet-mvc-integration to add you custom OCR component?

**Comment by MayueCif** [comment]
I've tried. It's still the same problem.

**Comment by dluc** [comment]
@MayueCif about the code at  https://github.com/microsoft/semantic-memory/tree/main/examples/007-aspnet-mvc-integration does that fail too?  I can run that code without issues, and hit the controller. To dig further I'd need to understand if the error occurs only when using `WithCustomImageOcr`. Thanks

**Comment by MayueCif** [comment]
You are using only ISemanticMemoryClient in this example , I need to use ImageDecoder, added IOcrEngine and this problem occurs. 
![image](https://github.com/microsoft/semantic-memory/assets/6133287/1514f6e6-62a8-453d-aea6-dc75fe0a85b9)

**Comment by dluc** [comment]
here's a working example with a custom OCR: https://github.com/dluc/semantic-memory/tree/issue67/examples/007-aspnet-mvc-integration

```csharp
ISemanticMemoryClient memory = new MemoryClientBuilder(builder.Services)
    .FromAppSettings()
    .WithCustomImageOcr(new MyOcrEngine())
    .Build();
```

Note the use of `FromAppSettings()`, so the config file needs all the right values.


```csharp
[ApiController]
[Route("[controller]")]
public class MemoryController : ControllerBase
{
    private readonly ISemanticMemoryClient _memory;
    private readonly IOcrEngine _ocr;

    public MemoryController(ISemanticMemoryClient memory, IOcrEngine ocr)
    {
        this._memory = memory;
        this._ocr = ocr;
    }

    [HttpGet(Name = "GetAnswer")]
    public async Task<string> GetAsync()
    {
        var ocrResult = await this._ocr.ExtractTextFromImageAsync(null);
        return ocrResult;
    }
}
```

![image](https://github.com/microsoft/semantic-memory/assets/371009/4b685b41-0a25-4bfe-b4e7-0e321d71e945)

**Comment by MayueCif** [comment]
I noticed where it was different. I am using WithOpenAIDefaults. Error Reporting:

System.AggregateException:“Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.SemanticMemory.Search.SearchClient Lifetime: Singleton ImplementationType: Microsoft.SemanticMemory.Search.SearchClient': Unable to resolve service for type 'Microsoft.SemanticMemory.MemoryStorage.ISemanticMemoryVectorDb' while attempting to activate 'Microsoft.SemanticMemory.Search.SearchClient'.) (Error while validating the service descriptor 'ServiceType: Microsoft.SemanticMemory.Pipeline.IPipelineOrchestrator Lifetime: Singleton ImplementationType: Microsoft.SemanticMemory.Pipeline.InProcessPipelineOrchestrator': Unable to resolve service for type 'Microsoft.SemanticMemory.ContentStorage.IContentStorage' while attempting to activate 'Microsoft.SemanticMemory.Pipeline.InProcessPipelineOrchestrator'.) (Error while validating the service descriptor 'ServiceType: Microsoft.SemanticMemory.Pipeline.InProcessPipelineOrchestrator Lifetime: Singleton ImplementationType: Microsoft.SemanticMemory.Pipeline.InProcessPipelineOrchestrator': Unable to resolve service for type 'Microsoft.SemanticMemory.ContentStorage.IContentStorage' while attempting to activate 'Microsoft.SemanticMemory.Pipeline.InProcessPipelineOrchestrator'.)”

```
ISemanticMemoryClient memory = new MemoryClientBuilder(builder.Services)
    //.FromAppSettings()
    .WithOpenAIDefaults("sk-XXXXXXX")
    .WithCustomImageOcr(new MyOcrEngine())
    .Build();
```

**Comment by dluc** [comment]
Working on a change that should help with your scenario

**Comment by MayueCif** [comment]
It should work, but I have a question, why define both memoryServiceCollection and hostServiceCollection at the same time?

**Comment by dluc** [comment]
it's mostly to isolate the builder and knowing that there's no external logic affecting it. Passing in a service collection is only to share-out what the builder sets up, there's no way to pass in a service collection asking the builder to use it.

If one prefers managing dependencies externally, we suggest not to use the builder, and go the classic way, calling ctors or having custom DI logic that sets up all the dependencies.

**Comment by dluc** [comment]
Thank you for your collaboration and contribution to this issue! As the matter at hand appears to be resolved, I'll be closing this issue for now. However, please don't hesitate to reach out if you have any further questions or concerns. We're more than happy to reopen the issue or continue the conversation as needed.

Wishing you all the best, and happy coding! 😊
