### ISSUE TITLE
"text-embedding-ada-003" Does not exist (yet)

### ISSUE THREAD

**Issue by Eddie-Hartman** [microsoft/semantic-memory#77]
It seems like some next-generation of ada was used for embedding, but afaik it doesn't exist yet publicly, so it causes errors to try and use. Likely references need updated to 002 instead at least until 003 is publicly released.

**Comment by crickman** [comment]
Thank you for reporting this Eddie.  It appears my outlook here was overly optimistic on the ada 003 availability.
